version: "3.7"

services:
  mysql:
    image: mysql:latest
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - "./data/database:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin
    networks:
      - my-network
    ports:
      - "9000:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
  redis:
    container_name: redis-01
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - my-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.production
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      - mysql
      - redis
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
