swagger: "2.0"
info:
  version: "1.0.0"
  title: "User API"
  description: "An API for managing users"
host: " http://localhost:8000"
basePath: "/"
schemes:
  - "https"
paths:
  /users:
    get:
      description: "Retrieve a list of users"
      parameters:
        - in: query
          name: "name"
          description: "The name of the user to search for"
          type: "string"
      responses:
        200:
          description: "A list of users"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
    post:
      description: "Create a new user"
      parameters:
        - in: body
          name: "user"
          description: "The user to create"
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "The created user"
          schema:
            $ref: "#/definitions/User"
  /auth/profile:
    get:
      responses:
        200:
          description: "A user profile"
          schema:
            type: object
            properties:
              username:
                type: string

definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
